# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160124_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cor_corda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Corda'),
        ),
    ]
