# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20160124_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='exame',
            name='bairro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='exame',
            name='cidade',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='exame',
            name='complemento',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='exame',
            name='logradouro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='exame',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupo',
            name='bairro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='grupo',
            name='cidade',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='grupo',
            name='complemento',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='grupo',
            name='logradouro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='grupo',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.DateField(default=0),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
