# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160125_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='aluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Grupo'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Professor'),
        ),
    ]
